EOG_PLUGIN_DIR = ~/.gnome2/eog/plugins

all: clean build

build: ;

clean: ;

install: ;

uninstall: ;

local-install:
	mkdir -p $(EOG_PLUGIN_DIR)
	cp zeitgeist.eog-plugin zeitgeist_plugin.py $(EOG_PLUGIN_DIR)

local-uninstall:
	-rm -rf $(EOG_PLUGIN_DIR)
