BZR_PLUGIN_DIR = ~/.bazaar/plugins/zeitgeist

all: clean build

build: ;

clean: ;

install: ;
	
uninstall: ;

local-install:
	mkdir -p $(BZR_PLUGIN_DIR)
	cp __init__.py $(BZR_PLUGIN_DIR)

local-uninstall:
	-rm -rf $(BZR_PLUGIN_DIR)
